github: "devconfig-pvt-ltd"
patreon: "devconfig-pvt-ltd"
open_collective: "devconfig-pvt-ltd"
ko_fi: "devconfig-pvt-ltd"
tidelift: "npm/devconfig-pvt-ltd"
community_bridge: "devconfig-pvt-ltd"
liberapay: "devconfig-pvt-ltd"
issuehunt: "devconfig-pvt-ltd"
lfx_crowdfunding: "devconfig-pvt-ltd"
polar: "devconfig-pvt-ltd"
buy_me_a_coffee: "devconfig-pvt-ltd"
thanks_dev: "devconfig"
# custom:
#   - "https://customsponsorship.com"
#   - "https://othersponsor.com"
